apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercises-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exercises-db
  template:
    metadata:
      labels:
        app: exercises-db
    spec:
      containers:
        - image: lorenzogl/exercises-db:GIT_SHA_SECRET
          imagePullPolicy: Always
          name: exercises-db
          env:
            - name: ENV_VAR_1
              value: ENV_VAR_1_VALUE

---
apiVersion: v1
kind: Service
metadata:
  name: exercises-db
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: "exercises-db"
      port: 5432
      targetPort: 5432
  selector:
    app: exercises-db
