apiVersion: v1
kind: PersistentVolume
metadata:
  name: exercises-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/postgresql/data/exercises-db"  # Adjust the path for each PostgreSQL instance

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exercises-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercises-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exercises-db
  template:
    metadata:
      labels:
        app: exercises-db
    spec:
      containers:
        - image: lorenzogl/exercises-db:GIT_SHA_SECRET
          imagePullPolicy: Always
          name: exercises-db
          env:
            - name: ENV_VAR_1
              value: ENV_VAR_1_VALUE
          volumeMounts:
            - name: exercises-db-storage
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: exercises-db-storage
          persistentVolumeClaim:
            claimName: exercises-db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: exercises-db
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: "exercises-db"
      port: 5432
      targetPort: 5432
  selector:
    app: exercises-db
