apiVersion: apps/v1
kind: Deployment
metadata:
  name: exercises-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exercises-service
  template:
    metadata:
      labels:
        app: exercises-service
    spec:
      containers:
        - image: lorenzogl/exercises-service:GIT_SHA_SECRET
          imagePullPolicy: Always
          name: exercises-service
          env:
            - name: ENV_VAR_1
              value: ENV_VAR_1_VALUE

---
apiVersion: v1
kind: Service
metadata:
  name: exercises-service
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
    - name: "exercises-service"
      port: 9000
      targetPort: 9000
  selector:
    app: exercises-service