name: Publish Docker Image + Deploy to Okteto
on:
  push:
    branches: [ master ]

jobs:
  publish-docker-image-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: lorenzogl/exercises-service
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ github.sha }}
          dockerfile: Dockerfile
  publish-docker-image-database:
    needs: publish-docker-image-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: lorenzogl/exercises-db
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: ${{ github.sha }}
          dockerfile: Dockerfile-db